### PR TITLE
Fix offsets

### PR DESCRIPTION
**Pull request by danischroeter**
fix offset misuse
    -the snapshot store and the event store are completely independent but the same offset was used
     ->split the offsets using lastOffset for the event stream and lastSnapshotOffset for the snapshots

### CODE REVIEW

**Comment by filosganga** [comment]
Good catch thanks.

You have to check the 2.11.8 compilation.

**Comment by danischroeter** [comment]
Well thank you for first providing this project!
I will update the fix pull request once forceUpdate is in...

**Comment by danischroeter** [comment]
Done... :)

**Comment by filosganga** [comment]
Thanks again for your contribution

**Comment by danischroeter** [comment]
Ahh you're right. Forget the pr.

**Pull request closed without merging**
